### ISSUE TITLE
Is there any guide about installation?

### ISSUE THREAD

**Issue by ziyigogogo** [MyCaffe/NCCL#1]
Hi there,
Thank you so much for the repo. Since I met a nccl problem on my windows machine.
But kinda confused by you repo how to use these things?
Thanks again.

**Comment by ZoroDerVonCodier** [comment]
@ziyigogogo The installation is pretty simple - you just need to make sure the DLL is in the directory of the application that uses it.  To see how we use the NCCL functions, please see https://github.com/MyCaffe/MyCaffe/blob/master/CudaDnnDLL/Cuda%20Files/nccl.cu 

I hope this helps!

**Comment by ZoroDerVonCodier** [comment]
One other note - we have found that the NCCL works best when all GPU's used are ALL in TCC mode.  For more about TCC mode, see https://docs.nvidia.com/gameworks/content/developertools/desktop/nsight/tesla_compute_cluster.htm

Not all GPU's support the TCC mode, but the Titan X, Titan Xp and Quadro RTX 8000 do.  Running nvidia-smi (https://developer.nvidia.com/nvidia-system-management-interface) will tell you whether or not the GPU(s) that you have support TCC or not. 

And for information on NCCL see https://devblogs.nvidia.com/fast-multi-gpu-collectives-nccl/

Hope this helps!

**Comment by ziyigogogo** [comment]
@ZoroDerVonCodier Thank you so for the links&notes. I will work on it.
