### ISSUE TITLE
when i run nccl.10.1.vcxproj, i get wrong. it notes that 

### ISSUE THREAD

**Issue by hesterLong** [MyCaffe/NCCL#2]
`nccl.10.1.vcxproj -> D:\NCCL-master\windows\x64\Release\nccl64_134.10.1.dll
  copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudart*.dll" "D:\NCCL-master\windows\x64\Release\"
  系统找不到指定的路径。`

in fact the file 'cudart64_101.dll' exists in 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\' 

do u know how to fit it? thanks!

**Comment by ZoroDerVonCodier** [comment]
Hi @hesterLong ,

Good catch!  We have corrected the CUDA_PATH in the final build step to the specific version used, which should fix this.

Thanks for your input!  Let us know if this fixes the issue and if so we will close this out.
