### ISSUE TITLE
how can I use this with tensorflow 

### ISSUE THREAD

**Issue by kaisKa** [MyCaffe/NCCL#3]
please if you could provide with steps that make me able using the library with tensorf flow

**Comment by ZoroDerVonCodier** [comment]
Hi @kaisKa ,

That is a good question - you will have to ask the Tensorflow people that one.  However, if you want to use it integrated with a Deep Learning AI Platform, check out https://github.com/MyCaffe/MyCaffe and in specific, see https://github.com/MyCaffe/MyCaffe/blob/master/MyCaffe/common/Parallel.cs and https://github.com/MyCaffe/MyCaffe/blob/master/CudaDnnDLL/Cuda%20Files/nccl.cu.

Another alternative is to just integrate MyCaffe directly using the MyCaffe Nuget Package at 
https://www.nuget.org/packages?q=MyCaffe 

Hope this helps!
