### ISSUE TITLE
.EXE's not in directory after build

### ISSUE THREAD

**Issue by jbrownmi88** [MyCaffe/NCCL#4]
Hello, I'm having an issue where the .exe files are not showing up in the directory after I build the project.  I'm trying to build the project for CUDA version 10.1.  I get no errors from VS, and it tells me the build is successful.  It creates nccl64_134.10.1.dll and copies cudart64_101.dll correctly, it just isn't creating the .exe files for some reason.  I thought they might be somewhere else, but they're nowhere to be found.  Any ideas?

**Comment by ZoroDerVonCodier** [comment]
Hi @jbrownmi88 ,

Good catch.  We have updated these to use CUDA 10.1 for now and also updated the Target Platform to 10.0.17763 (for compatibility with the NCCL version 10.1 builds) and now use the VS2017 v141 Platform Toolset.  In the near future, we will be upgrading these to the new CUDA 11.1.

The EXE builds are now placed in the ..\NCCL\windows\x64\Release (and Debug) directories.

Thanks for the input.  Let us know if these work for you and we will close the project after hearing from you.

**Comment by jbrownmi88** [comment]
Hi Dave, thanks for the response.  I'm still having the same issue even with the new build.  Here is the output for the build:

1>------ Build started: Project: nccl.10.1, Configuration: Debug x64 ------
1>Compiling CUDA source file ..\src\all_gather.cu...
1>Compiling CUDA source file ..\src\all_reduce.cu...
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\all_gather.cu.obj "C:\Users\jbrown\NCCL-master\src\all_gather.cu"
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\all_reduce.cu.obj "C:\Users\jbrown\NCCL-master\src\all_reduce.cu"
1>Compiling CUDA source file ..\src\core.cu...
1>Compiling CUDA source file ..\src\libwrap.cu...
1>Compiling CUDA source file ..\src\broadcast.cu...
1>Compiling CUDA source file ..\src\reduce.cu...
1>Compiling CUDA source file ..\src\reduce_scatter.cu...
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\core.cu.obj "C:\Users\jbrown\NCCL-master\src\core.cu"
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\libwrap.cu.obj "C:\Users\jbrown\NCCL-master\src\libwrap.cu"
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\reduce.cu.obj "C:\Users\jbrown\NCCL-master\src\reduce.cu"
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\reduce_scatter.cu.obj "C:\Users\jbrown\NCCL-master\src\reduce_scatter.cu"
1>C:/Users/jbrown/NCCL-master/src/core.cu(176): warning : offsetof applied to non-POD types is nonstandard
1>C:/Users/jbrown/NCCL-master/src/core.cu(241): warning : offsetof applied to non-POD types is nonstandard
1>libwrap.cu
1>Done building project "nccl.10.1.vcxproj".
1>C:/Users/jbrown/NCCL-master/src/core.cu(176): warning : offsetof applied to non-POD types is nonstandard
1>C:/Users/jbrown/NCCL-master/src/core.cu(241): warning : offsetof applied to non-POD types is nonstandard
1>
1>C:\Users\jbrown\NCCL-master\windows>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_53,code=\"sm_53,compute_53\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared  -g   -DCOMPILING_NCCL -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\obj.10.1d\vc141.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\obj.10.1d\broadcast.cu.obj "C:\Users\jbrown\NCCL-master\src\broadcast.cu"
1>core.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>C:/Users/jbrown/NCCL-master/src/core.cu(244): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'size_t'
1>C:/Users/jbrown/NCCL-master/src/core.cu(244): note: consider using '%zd' in the format string
1>C:/Users/jbrown/NCCL-master/src/core.cu(257): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
1>C:/Users/jbrown/NCCL-master/src/core.cu(257): note: consider using '%zu' in the format string
1>C:/Users/jbrown/NCCL-master/src/core.cu(277): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
1>C:/Users/jbrown/NCCL-master/src/core.cu(277): note: consider using '%zu' in the format string
1>C:/Users/jbrown/NCCL-master/src/core.cu(288): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
1>C:/Users/jbrown/NCCL-master/src/core.cu(288): note: consider using '%zu' in the format string
1>C:/Users/jbrown/NCCL-master/src/core.cu(668): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
1>C:/Users/jbrown/NCCL-master/src/core.cu(668): note: consider using '%zu' in the format string
1>Done building project "nccl.10.1.vcxproj".
1>all_gather.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>c:\users\jbrown\nccl-master\src\common_coll.h(102): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:/Users/jbrown/NCCL-master/src/all_gather.cu(179): note: see reference to function template instantiation 'void ArgsSetup<unsigned __int64>(KernelArgs<unsigned __int64> *,const void *,void *,const int,const int,ncclComm *)' being compiled
1>C:/Users/jbrown/NCCL-master/src/all_gather.cu(191): note: see reference to function template instantiation 'ncclResult_t RingAllGather<FuncNull<unsigned __int64>,T>(const void *,void *,const int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64
1>        ]
1>C:/Users/jbrown/NCCL-master/src/all_gather.cu(190): note: while compiling class template member function 'ncclResult_t AllGather<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)'
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to function template instantiation 'ncclResult_t AllGather<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to class template instantiation 'AllGather<T,Op>' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(78): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,unsigned __int64,Op>(const void *,void *,int,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=AllGather,
1>            Op=FuncNull
1>        ]
1>C:/Users/jbrown/NCCL-master/src/all_gather.cu(200): note: see reference to function template instantiation 'ncclResult_t enqueue<AllGather,FuncNull>(const void *,void *,int,ncclDataType_t,int,ncclComm_t,cudaStream_t)' being compiled
1>Done building project "nccl.10.1.vcxproj".
1>broadcast.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>c:\users\jbrown\nccl-master\src\common_coll.h(102): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:/Users/jbrown/NCCL-master/src/broadcast.cu(141): note: see reference to function template instantiation 'void ArgsSetup<unsigned __int64>(KernelArgs<unsigned __int64> *,const void *,void *,const int,const int,ncclComm *)' being compiled
1>C:/Users/jbrown/NCCL-master/src/broadcast.cu(153): note: see reference to function template instantiation 'ncclResult_t RingBroadcast<FuncNull<unsigned __int64>,T>(void *,const int,const int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64
1>        ]
1>C:/Users/jbrown/NCCL-master/src/broadcast.cu(152): note: while compiling class template member function 'ncclResult_t Broadcast<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)'
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to function template instantiation 'ncclResult_t Broadcast<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to class template instantiation 'Broadcast<T,Op>' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncNull
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(78): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,unsigned __int64,Op>(const void *,void *,int,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=Broadcast,
1>            Op=FuncNull
1>        ]
1>C:/Users/jbrown/NCCL-master/src/broadcast.cu(162): note: see reference to function template instantiation 'ncclResult_t enqueue<Broadcast,FuncNull>(const void *,void *,int,ncclDataType_t,int,ncclComm_t,cudaStream_t)' being compiled
1>Done building project "nccl.10.1.vcxproj".
1>reduce.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>c:\users\jbrown\nccl-master\src\common_coll.h(102): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:/Users/jbrown/NCCL-master/src/reduce.cu(125): note: see reference to function template instantiation 'void ArgsSetup<unsigned __int64>(KernelArgs<unsigned __int64> *,const void *,void *,const int,const int,ncclComm *)' being compiled
1>C:/Users/jbrown/NCCL-master/src/reduce.cu(137): note: see reference to function template instantiation 'ncclResult_t RingReduce<FuncMin<unsigned __int64>,T>(const void *,void *,const int,const int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64
1>        ]
1>C:/Users/jbrown/NCCL-master/src/reduce.cu(136): note: while compiling class template member function 'ncclResult_t ReduceFunctor<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)'
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to function template instantiation 'ncclResult_t ReduceFunctor<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to class template instantiation 'ReduceFunctor<T,Op>' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(78): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,unsigned __int64,Op>(const void *,void *,int,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=ReduceFunctor,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(104): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,FuncMin>(const void *,void *,int,ncclDataType_t,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=ReduceFunctor
1>        ]
1>C:/Users/jbrown/NCCL-master/src/reduce.cu(146): note: see reference to function template instantiation 'ncclResult_t enqueue<ReduceFunctor>(const void *,void *,int,ncclDataType_t,ncclRedOp_t,int,ncclComm_t,cudaStream_t)' being compiled
1>Done building project "nccl.10.1.vcxproj".
1>reduce_scatter.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>c:\users\jbrown\nccl-master\src\common_coll.h(102): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:/Users/jbrown/NCCL-master/src/reduce_scatter.cu(142): note: see reference to function template instantiation 'void ArgsSetup<unsigned __int64>(KernelArgs<unsigned __int64> *,const void *,void *,const int,const int,ncclComm *)' being compiled
1>C:/Users/jbrown/NCCL-master/src/reduce_scatter.cu(154): note: see reference to function template instantiation 'ncclResult_t RingReduceScatter<FuncMin<unsigned __int64>,T>(const void *,void *,const int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64
1>        ]
1>C:/Users/jbrown/NCCL-master/src/reduce_scatter.cu(153): note: while compiling class template member function 'ncclResult_t ReduceScatter<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)'
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to function template instantiation 'ncclResult_t ReduceScatter<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to class template instantiation 'ReduceScatter<T,Op>' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(78): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,unsigned __int64,Op>(const void *,void *,int,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=ReduceScatter,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(104): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,FuncMin>(const void *,void *,int,ncclDataType_t,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=ReduceScatter
1>        ]
1>C:/Users/jbrown/NCCL-master/src/reduce_scatter.cu(163): note: see reference to function template instantiation 'ncclResult_t enqueue<ReduceScatter>(const void *,void *,int,ncclDataType_t,ncclRedOp_t,int,ncclComm_t,cudaStream_t)' being compiled
1>Done building project "nccl.10.1.vcxproj".
1>all_reduce.cu
1>c:\users\jbrown\nccl-master\src\common_coll.h(25): warning C4996: 'cudaPointerAttributes::memoryType': was declared deprecated
1>c:\program files\nvidia gpu computing toolkit\cuda\v10.1\include\driver_types.h(1302): note: see declaration of 'cudaPointerAttributes::memoryType'
1>c:\users\jbrown\nccl-master\src\common_coll.h(102): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>C:/Users/jbrown/NCCL-master/src/all_reduce.cu(211): note: see reference to function template instantiation 'void ArgsSetup<unsigned __int64>(KernelArgs<unsigned __int64> *,const void *,void *,const int,const int,ncclComm *)' being compiled
1>C:/Users/jbrown/NCCL-master/src/all_reduce.cu(223): note: see reference to function template instantiation 'ncclResult_t RingAllReduce<FuncMin<unsigned __int64>,T>(const void *,void *,const int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64
1>        ]
1>C:/Users/jbrown/NCCL-master/src/all_reduce.cu(222): note: while compiling class template member function 'ncclResult_t AllReduce<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)'
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to function template instantiation 'ncclResult_t AllReduce<T,Op>::entry(const void *,void *,int,int,ncclComm *,cudaStream_t)' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(41): note: see reference to class template instantiation 'AllReduce<T,Op>' being compiled
1>        with
1>        [
1>            T=unsigned __int64,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(78): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,unsigned __int64,Op>(const void *,void *,int,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=AllReduce,
1>            Op=FuncMin
1>        ]
1>c:\users\jbrown\nccl-master\src\enqueue.h(104): note: see reference to function template instantiation 'ncclResult_t enqueue<ColFunc,FuncMin>(const void *,void *,int,ncclDataType_t,int,ncclComm_t,cudaStream_t)' being compiled
1>        with
1>        [
1>            ColFunc=AllReduce
1>        ]
1>C:/Users/jbrown/NCCL-master/src/all_reduce.cu(232): note: see reference to function template instantiation 'ncclResult_t enqueue<AllReduce>(const void *,void *,int,ncclDataType_t,ncclRedOp_t,int,ncclComm_t,cudaStream_t)' being compiled
1>Done building project "nccl.10.1.vcxproj".
1>   Creating library C:\Users\jbrown\NCCL-master\windows\x64\Debug\nccl64_134.10.1.lib and object C:\Users\jbrown\NCCL-master\windows\x64\Debug\nccl64_134.10.1.exp
1>nccl.10.1.vcxproj -> C:\Users\jbrown\NCCL-master\windows\x64\Debug\nccl64_134.10.1.dll
1>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudart*.dll" "C:\Users\jbrown\NCCL-master\windows\x64\Debug\"
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudart32_101.dll
1>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudart64_101.dll
1>        2 file(s) copied.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**EDIT:** I redownloaded the build and changed the pathway from NCCL-master to NCCL, and rebuilt each exe individually and now they are in the Debug directory.

**Comment by ZoroDerVonCodier** [comment]
Hi @jbrownmi88 ,

Try loading the nccl.sln at https://github.com/MyCaffe/NCCL/blob/master/windows/nccl.sln.  You should then be able to build each of the EXE's from the projects in the 'Test' folder.

Let us know if this helps!
